# Generated by Django 3.0.14 on 2021-11-10 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fanfics', '0002_auto_20211110_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='image',
        ),
    ]
