# Generated by Django 3.0.14 on 2021-11-16 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanfics', '0005_auto_20211114_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
