# Generated by Django 3.0.14 on 2021-11-24 16:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fanfics', '0006_publication_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='users_like',
            field=models.ManyToManyField(blank=True, related_name='publication_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
